version: '3.8'

services:
  backend:
    build:
      context: ./todos-app-backend
      dockerfile: Dockerfile
    environment:
      MONGODB_CONNECTION_URL: mongodb://mongodb:27017/todos
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./todos-app-frontend
      dockerfile: Dockerfile
    environment:
      VITE_BACKEND_BASE_URL: http://localhost:3000
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:5.0.5
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: